package com.bridge.agent.core.plan;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Structured execution plan generated by the planner.
 */
public record ExecutionPlan(
        @JsonProperty("phases") List<PlanPhase> phases
) {
    public List<PlanPhase> phases() {
        return phases == null ? List.of() : phases;
    }
}
