package com.bridge.agent.runtime;

public enum AgentEventType {
    RUN_STARTED,
    RUN_RESUMED,
    LLM_STARTED,
    LLM_COMPLETED,
    TOOL_STARTED,
    TOOL_COMPLETED,
    TOOL_FAILED,
    TOOL_RETRIED,
    STEP_RECORDED,
    REPLAN_TRIGGERED,
    HANDOFF,
    GUARDRAIL_WARNING,
    APPROVAL_REQUIRED,
    APPROVAL_RESOLVED,
    CHECKPOINT_SAVED,
    CHECKPOINT_LOADED,
    RAG_TRACE,
    MEMORY_READ,
    MEMORY_WRITTEN,
    RUN_FINISHED
}
